sudo: false
language: node_js
node_js:
- node
- 8
script:
- npm run lint
- npm run test
- npm run build

aliases:
  deploy: &deploy
    provider: heroku
    api_key:
      secure: SkKOVBnCuDyAnI6cZgK/8yUnpZhC1BB0ui1hhIGreHpx9suW+lla1YUXPlDmTcyB1hWDHYZGKn3GxUw9hEfsxnplJNTcAaNI10A3EyRUVDiZ+9v1gZAixjmm/DPBvZUvwrdR8MaqXgWIVD1Fvywv/e7INi5qGr3Q+/BBmX1hrRPB6CzofDOz6sDtnSZF7kL5nIXB63RELb7LqbScXe6H8QbUZd+TAbdZFx5Yn8Hh3+kLTiCeJxeETyVG4iXCNWN+x8ZW3erbQfKN1yN4dNJMZ6O/e3G6qT3sq11XKtV8vOpdcQRuW954vuDq5E+GcSLo0Fcqa3RFjbECigIwBSZBcxWCPF3w7XXiuyi4oAE7ByFfQ65MiCzBRKLZpIVflOEr7LsDKOOUP1aKFFgrd1mKkGhne+p5+7vOfSGYT7nlhXQbyhRvoX81eRtHJreGwYz6NDfCsoy2opWUWbCV44uxdyUI+pf3DF9rNfD10Ib+e29HvHS3aoQBPA2lXhYu0dLVjnhinlN4gswc3vRkfcoOQb9aA7ZXUIfaD99Kyif4OAimmA7SeW6eM+KvtO+N99SEnhZC6eX81bas5hfPnfS3CPyinqHOIhdTwlD73D7JBqcRiX3P37t5VllGLfzoQusmoE+1pAEPU5trackr9tE1MXyxRn+lQYYR6JTsbAZbw+8=
    skip_cleanup: true

jobs:
  include:
    - stage: Deploy (development)
      if: tag IS blank
      script:
        - npm run build
      deploy:
        <<: *deploy
        app: shri-node-awesome-master

    - stage: Deploy (production)
      if: tag IS present
      script:
        - npm run build
      deploy:
        <<: *deploy
        app: shri-node-awesome-production
        on:
          tags: true
